// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARBPunpX28F5m75Ns3pq7Nw536BaW7uNY',
    appId: '1:20766843959:web:2871662252494a27634bb2',
    messagingSenderId: '20766843959',
    projectId: 'supermarket-b8e11',
    authDomain: 'supermarket-b8e11.firebaseapp.com',
    storageBucket: 'supermarket-b8e11.firebasestorage.app',
    measurementId: 'G-QV5ZDWSH21',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCT2nHJJI0UfH14--6K4fWqv-WF3u5kjSg',
    appId: '1:20766843959:android:a93c6f16d484e561634bb2',
    messagingSenderId: '20766843959',
    projectId: 'supermarket-b8e11',
    storageBucket: 'supermarket-b8e11.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCaE8yrSc4ENWu4AuD1bMRNw5820-D3GKQ',
    appId: '1:20766843959:ios:79698e8d7f275f3b634bb2',
    messagingSenderId: '20766843959',
    projectId: 'supermarket-b8e11',
    storageBucket: 'supermarket-b8e11.firebasestorage.app',
    iosClientId: '20766843959-16bk8q44nlq6nbbb3d0ecr45hh8970q7.apps.googleusercontent.com',
    iosBundleId: 'com.example.testfire',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCaE8yrSc4ENWu4AuD1bMRNw5820-D3GKQ',
    appId: '1:20766843959:ios:79698e8d7f275f3b634bb2',
    messagingSenderId: '20766843959',
    projectId: 'supermarket-b8e11',
    storageBucket: 'supermarket-b8e11.firebasestorage.app',
    iosClientId: '20766843959-16bk8q44nlq6nbbb3d0ecr45hh8970q7.apps.googleusercontent.com',
    iosBundleId: 'com.example.testfire',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyARBPunpX28F5m75Ns3pq7Nw536BaW7uNY',
    appId: '1:20766843959:web:7106b353468fa2a4634bb2',
    messagingSenderId: '20766843959',
    projectId: 'supermarket-b8e11',
    authDomain: 'supermarket-b8e11.firebaseapp.com',
    storageBucket: 'supermarket-b8e11.firebasestorage.app',
    measurementId: 'G-SZ8FQ05838',
  );

}